import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import norm


sns.set()



# populacja n - 5 osób
# X - zmienna losowa - badana cecha populacji, x1, x2 - wartosci cechy


# PRZYKŁAD DYSKRETNY - OCENY POSZCZEGOLNYCH STUDENTOW - USTALONE SĄ KONKRETNE WARTOŚCI, CECHA NIE MOZE PRZYJAC DOWOLNEJ
# BADANA CECHA - OCENA
# REALIZACJA ZMIENNEJ:
X = np.array([3,4.5,5,4.5,3])
X

# PRZYKLAD DANE CIAGLE - WZROST STUDENTA - WZROST JEST ZMIENNA CIAGLA 
# # BADANA CECHA - WZROST
# REALIZACJA ZMIENNEJ:
X = np.array([182,175.1,174,181.5,155])
X


# MIARY TENDENCJI CENTRALNEJ
# ŚREDNIA TO SUMA EL / LICZBA EL
X.mean()


# MEDIANA TO SRODKKOWY WYRAZ CIAGU W PRZYPADKU KIEDY LICZBA EL CIAGU JEST NIEPARZYSTA, KIEDY JEST PARZYSTA TO SR 2 SRODKOWYCH ELEMENTOW
# NAJPIERW PORZADKUJEMY CIAG NASTEPNIE WYBIERAMY EL SRODKOWY LUB SR 2 SRODKOWYCH

np.median(X)


# DOMINANTA (MODA) TO NAJCZESCIEJ WYSTEPUJACA WARTOSC W CIAGU




# MIARY ROZRZUTU

# SREDNI BLAD 
# SREDNIA ODLEGLOSC OD SREDNIEJ
b_X = 1/len(X) * abs(X-X.mean()).sum()



# WARIANCJA TO ŚREDNI BLAD DO KWADRATU, BARDZIEJ "KARA" ZA WARTOSCI BARDZIEJ ODDALONE

var_X = 1/len(X) * ((X-X.mean())**2).sum()


# KWANTYL RZEDU P DZIELI UPORZADKOWANY CIAG WARTOSCI NA DWIE CZESCI W PROPORCJACH P ORAZ 1-P
# MEDIANA TO KWANTYL 0.5

# DYSTRYBUANTA EMPIRYCZNA TO LICZEBNOSC ZBIORU ELEMENTOW MNIEJSZYCH OD PODANEGO X PODZIELONA PRZEZ LICZBE EL ZBIORU

# PRZESTRZEN PROBABILISTYCZNA TO :
# TROJKA OMEGA, F, P
# OMEGA - TO ZBIOR, PRZESTRZEN ZDARZEN
# F - TO RODZINA PODZBIOROW OMEGA
# P - TO PRAWDOPODOBIENSTWO, FUNKCJA DZIALA NA ZBIORZE OMEGA I PRZYPISUJE WARTOSCI RZECZYWISTE
# ELEMENTY ZBIORU OMEGA TO ZADRZENIA ELEMENTARNE


# PRZESTRZEN KLASYCZNA 
# OMEGA TO SKONCZONA PRZESTRZEN ZDARZEN ELEMENTARNYCH 
# PRAWDOPODONIENSTWO A TO LICZBA ELEMENTOW PODZBIORU A PODZIELONA PRZEZ LICZBE ELEMENTOW CALEGO ZBIORU N

# ZDARZENIA NIEZALEZNE TO TAKIE KIEDY PRAWDOPODOBIENSTWO ILOCZYNU JEST ROWNE ILOCZYNOWI PRAWDPOPODOBIENSTW


omega = np.array((1,2,3,4,5,6))
A = set([x for x in omega if x%2==0])
P_A = len(A)/len(omega)
P_A

B = set([x for x in omega if x>4])
P_B = len(B)/len(omega)

PA_PB = P_A * P_B
intersection_AB = set.intersection(A, B)
P_intersection_AB = len(intersection_AB)/len(omega)

print('Przeciecie zbiorów: ', intersection_AB)
print('Iloczyn prawdopodobienstw zdarzen A i B: ', PA_PB)
print('Prawdopodobienstwo iloczynu zdarzen A i B: ', P_intersection_AB)


# DWIE ZMIENNE SA NIEZALEZNE KIEDY DLA 2 ZBIOROW ZACHODZI WARUNEK NIEZALEZNOSCI

# PRAWDOPODOBIENSTWO WARUNKOWE A|B TO P(A^B)/P(B)
A
B
# PRAWDOPODOBIENSTWO WYLOSOWANIA LICZBY PARZYSTEJ(A) POD WARUNKIEM WYLOSOWANIA LICZBY WIEKSZEJ NIZ 4(B)
PA_COND_B = P_intersection_AB / P_B
PA_COND_B







# ZAMIENNA LOSOWA I CHARAKTERYSTYKI ZMIENNEJ

# ZMIENNA LOSOWA TO FUNKCJA KTORA DZIALA NA DANYCH ELEMENTARNYCH

# DYSTRYBUANTA W PUNKCIE 1/2 TO PRAWDOPODOBIENSTWO X <= 1/2
# FUNKCJA GESTOSCI TO POCHODNA OD DYSTRYBUANTY

# KOWARAIANCJA X, Y TO ILOCZYN ZMIENNEJ X - SR X * Y- SR Y
# MOWI O POWIAZANIU JEDNEJ ZMIENNEJ Z DRUGA

# KORELACJA TO COV PODZIELONA NA ILOCZYN ODCHYLEN STANDARDOWYCH ZMIENNYCH

# BLAD STANDARDOWY TO ODCHYLENIE STANDARDOWE / PIERW Z N

X = [0, 1, 2, 3]
PX = [0.5, 0.3, 0.15, 0.05]


# WARTOSC OCZEKIWANA
EX = 0*0.5 + 1*0.3 + 2*0.15 + 3*0.05
EX
EX = sum([x*y for x,y in zip(X,PX)])
EX

VAR_X = (0-EX)**2*0.5 + (1-EX)**2*0.3 + (2-EX)**2*0.15 + (3-EX)**2*0.05
VAR_X

STD_X = np.sqrt(VAR_X)
STD_X

x = np.random.randn(5)
y = np.random.randn(5)

x.mean()
x.std()

np.corrcoef(x,y)




mu = 0
sigma = 1
x = np.linspace(mu - 3 * sigma, mu + 3 * sigma, 100)

plt.figure(figsize=(10,10))
plt.plot(x, norm.pdf(x, mu, sigma))
plt.figure(figsize=(10,10))
params = [(0,1),(0,2),(0,0.5)]

plt.figure(figsize=(10,10))
for mu, sigma in params:
    plt.plot(x, norm.pdf(x, mu, sigma))
    
    